### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by pslacerda** [conda-forge/fpocket-feedstock#30]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Support for Windows OS is not provided. The documentation says that

> By default, we build packages for macOS, Linux AMD64 and Windows AMD64. Other architectures are also available on request (e.g. Apple Silicon, PowerPC, Linux ARM).

This isn't happening.

### Installed packages

```shell
None.
```

### Environment info

```shell
Any Windows OS.
```

**Comment by simonbray** [comment]
fpocket doesn't support Windows as far as I know. There is an already an issue upstream requesting it (https://github.com/Discngine/fpocket/issues/106), so I will close this one.
